var sounds;

sounds = [
  {src: 'crickets.mp3', img: 'cricket.jpg', id: 'crickets', title: 'Crickets'},
  {src: 'downer.mp3', img: 'sadtrombone.jpg', id: 'downer', title: 'Downer'},
  {src: 'rimshot.mp3', img: 'rimshot.jpg', id: 'rimshot', title: 'Rimshot'},
  {src: 'shame.mp3', img: 'shame.jpg', id: 'shame', title: 'Shame'},
  {src: 'hodor.mp3', img: 'hodor.jpg', id: 'hodor', title: 'Hodor'},
  {src: 'youlose.mp3', img: 'badluckbrian.jpg', id: 'brian', title: 'Youlose'},
  {src: 'tim.mp3', img: 'tim.jpg', id: 'tim', title: 'Tim'},
  {src: 'whip.mp3', img: 'whip.jpg', id: 'whip', title: 'Whip'},
  {src: 'tripod.mp3', img: 'tripod.jpg', id: 'tripod', title: 'Tripod', cost: 2},
  {src: 'nein.mp3', img: 'nein.jpg', id: 'nein', title: 'Nein'},
  {src: 'scream.mp3', img: 'scream.jpg', id: 'scream', title: 'Scream'},
  {src: 'intel.mp3', img: 'intel.jpg', id: 'intel', title: 'Intel'},
  {src: 'winxp.mp3', img: 'winxp.jpg', id: 'winxp', title: 'Windows XP'},
  {src: 'turks.mp3', img: 'turks.jpg', id: 'turks', title: 'Turks Fruit', cost: 2},
  {src: 'dramatic.mp3', img: 'dramatic.jpg', id: 'dramatic', title: 'Dramatic'},
  {src: 'wrong.mp3', img: 'wrong.jpg', id: 'wrong', title: 'Wrong'},
  {src: 'michael.mp3', img: 'michael.jpg', id: 'michael', title: 'Michael'},
  {src: 'chopper.mp3', img: 'chopper.jpg', id: 'chopper', title: 'Chopper'},
  {src: 'duifmeneer.mp3', img: 'duifmeneer.jpg', id: 'duifmeneer', title: 'Duifmeneer'},
  {src: 'snoop.mp3', img: 'snoop.jpg', id: 'snoop', title: 'Snoop'},
  {src: 'giggity.mp3', img: 'giggity.jpg', id: 'giggity', title: 'Giggity'},
  {src: 'sorry.mp3', img: 'sorry.jpg', id: 'sorry', title: 'Sorry'},
  {src: '20thcentury.mp3', img: '20thcentury.jpg', id: '20thcentury', title: '20th Century Fox', cost: 3},
  {src: 'jurassic.mp3', img: 'jurassic.jpg', id: 'jurassic', title: 'Jurassic Park', cost: 3},
  {src: 'biem.mp3', img: 'biem.jpg', id: 'biem', title: 'BIEM!!!'},
  {src: 'icq.mp3', img: 'icq.jpg', id: 'icq', title: 'Uh-oh', cost: 0},
  {src: 'bert.mp3', img: 'bert.jpg', id: 'bert', title: 'Heee Bert!'},
  {src: 'hahabier.mp3', img: 'hahabier.jpg', id: 'hahabier', title: 'Ha Ha bier!'},
  {src: 'tirol.mp3', img: 'tirol.jpg', id: 'tirol', title: 'Absolut Tirol'},
  {src: 'overdracht.mp3', img: 'overdracht.jpg', id: 'overdracht', title: 'OVERDRACHT!'},
  {src: 'power.mp3', img: 'power.jpg', id: 'power', title: 'I\'ve got the power'},
  {src: 'mario.mp3', img: 'mario.jpg', id: 'mario', title: 'Super Mario Bross', cost: 3},
  {src: 'kingoflosers.mp3', img: 'kingoflosers.jpg', id: 'loserking', title: 'King of the losers', cost: 2},
  {src: 'kluis.mp3', img: 'kluis.jpg', id: 'kluis', title: 'kluis', cost: 1},
  {src: 'woodpecker.mp3', img: 'woodpecker.jpg', id: 'woodpecker', title: 'Woody', cost: 1},
  {src: 'bright.mp3', img: 'bright.jpg', id: 'bright', title: 'Bright Light', cost: 1},
  {src: 'goedzo.mp3', img: 'goedzo.jpg', id: 'goedzo', title: 'Wel Goed Zo Hoor!', cost: 1},
  {src: 'water.mp3', img: 'water.jpg', id: 'water', title: 'Water?', cost: 1},
  {src: 'buma.mp3', img: 'buma.jpg', id: 'buma', title: 'Dat is toch niet te geloven?', cost: 1},
  {src: 'goodmorning.mp3', img: 'goodmorning.jpg', id: 'goodmorning', title: 'Good Morning', cost: 1},
  // Keep hidden: true at end to not show hints in shortcuts
  {src: 'maniacal.mp3', img: 'maniacal.jpg', id: 'maniacal', title: 'Maniacal', hidden:true},
  {src: 'gaaay.mp3', img: 'gaaay.jpg', id: 'gaaay', title: 'Gaaay', hidden: true},
  {src: 'pieper.mp3', img: 'pieper.jpg', id: 'pieper', title: 'Pieper', hidden: true, cost: 5},
];
module.exports = sounds;
